services:

  ubuntu:
    container_name: sysadmin-nodrama-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      target: ubuntu
    ports:
      - 127.0.0.1:2222:22
    volumes:
      - ./scripts:/opt/scripts
    deploy:
      resources:
        limits:
          memory: 8192M
    #privileged: true
